# Generated by Django 5.1.2 on 2024-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='referencia_contrato',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
