# Generated by Django 5.1.2 on 2024-10-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_remove_contrato_ativo_remove_contrato_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='contrato_file',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
