# Generated by Django 5.1.2 on 2024-10-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_contrato_file_contrato_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
