# Generated by Django 5.1.2 on 2024-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contrato_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_reajuste',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('avista', 'A vista'), ('parcelado', 'Parcelado')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='indice_reajuste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='obervacao_pagamento',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='obervacao_rateio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='obervacao_reajuste',
            field=models.TextField(blank=True, choices=[('igpm', 'IGPM'), ('reajustado', 'Reajustado'), ('sem_reajuste', 'Sem reajuste')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='obervacao_valor',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observacao_contrato',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pasta_biblioteca',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('encerrado', 'Encerrado')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_gasto',
            field=models.CharField(blank=True, choices=[('imobilizado', 'Imobilizado'), ('despesa', 'Despesa')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='referencia_contrato',
            field=models.CharField(blank=True, editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('encerrado', 'Encerrado')], max_length=10, null=True),
        ),
    ]
