# Generated by Django 5.1.2 on 2024-10-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_pastabiblioteca_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastaBiblioteca',
            new_name='Pasta_biblioteca',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='observacao_pagamento',
            new_name='obervacao_pagamento',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='observacao_rateio',
            new_name='obervacao_rateio',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='observacao_reajuste',
            new_name='obervacao_reajuste',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='observacao_valor',
            new_name='obervacao_valor',
        ),
    ]
