# Generated by Django 5.1.2 on 2024-10-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_rename_pastabiblioteca_pasta_biblioteca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
