# Generated by Django 5.1.2 on 2024-10-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_alter_contrato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='pasta_biblioteca',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('encerrado', 'Encerrado')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='obervacao_reajuste',
            field=models.TextField(blank=True, choices=[('igpm', 'IGPM'), ('reajustado', 'Reajustado'), ('sem_reajuste', 'Sem reajuste')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='referencia_contrato',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
        migrations.DeleteModel(
            name='Pasta_biblioteca',
        ),
    ]
