# Generated by Django 5.1.2 on 2024-10-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_alter_contrato_pasta_biblioteca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='obervacao_pagamento',
            new_name='observacao_pagamento',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='obervacao_rateio',
            new_name='observacao_rateio',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='obervacao_valor',
            new_name='observacao_valor',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='obervacao_reajuste',
        ),
        migrations.AddField(
            model_name='contrato',
            name='observacao_reajuste',
            field=models.CharField(blank=True, choices=[('igpm', 'IGPM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.categoria'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='referencia_contrato',
            field=models.CharField(blank=True, editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pasta_biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.pastabiblioteca'),
        ),
    ]
