# Generated by Django 5.1.2 on 2024-10-21 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_fornecedor_alter_contrato_nome_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_contabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_contabil', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='c_contabil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.c_contabil'),
        ),
    ]
