# Generated by Django 5.1.2 on 2024-10-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_alter_contrato_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_contabil',
            old_name='C_contabil',
            new_name='nome',
        ),
    ]
