# Generated by Django 5.1.2 on 2024-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_contrato_criador_contrato_visibilidade_privada'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='flag_encerrar',
            field=models.BooleanField(default=False),
        ),
    ]
