# Generated by Django 5.1.2 on 2024-10-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_contrato_flag_encerrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='flag_encerrar',
        ),
    ]
