# Generated by Django 5.1.2 on 2024-10-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_alter_contrato_observacao_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='indice_reajuste',
            field=models.CharField(blank=True, choices=[('igpm', 'IGPM'), ('ipca', 'IPCA'), ('inpc', 'INPC'), ('outros', 'Outros')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observacao_reajuste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
