# Generated by Django 5.1.2 on 2024-10-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_alter_contrato_indice_reajuste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='renovacao_automatica',
            field=models.BooleanField(default=False),
        ),
    ]
