# Generated by Django 5.1.2 on 2024-10-31 14:31

import cnpj_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0027_contrato_anexo_distrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=cnpj_field.models.CNPJField(max_length=14),
        ),
    ]
