# Generated by Django 5.1.2 on 2024-10-31 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0028_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Apenas números são permitidos no campo de telefone.')]),
        ),
    ]
