# Generated by Django 5.1.2 on 2024-11-01 18:12

import cnpj_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0030_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=cnpj_field.models.CNPJField(max_length=15),
        ),
    ]
