# Generated by Django 5.1.2 on 2024-11-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0031_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
    ]
