# Generated by Django 5.1.2 on 2024-11-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0033_historicocontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocontrato',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato'),
        ),
    ]
