# Generated by Django 5.1.2 on 2024-11-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0034_alter_historicocontrato_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocontrato',
            name='campos_alterados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
