# Generated by Django 5.1.2 on 2024-11-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0036_alter_categoria_c_contabil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='observacao_rateio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='observacao_reajuste',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
