# Generated by Django 5.1.2 on 2024-12-03 12:09

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0039_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cpf',
            field=cpf_field.models.CPFField(default=0, max_length=14, verbose_name='cpf'),
            preserve_default=False,
        ),
    ]
