# Generated by Django 5.1.2 on 2024-12-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0041_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='lida',
            new_name='lido',
        ),
    ]
